### ISSUE TITLE
What's causing the CI error on the dev-pkgs workflow?

### ISSUE THREAD

**Issue by Robinlovelace** [geocompx/geocompr#937] opened 2023-03-05 23:30 UTC
The `dev-pkgs` workflow has been failing for many days and I'm curious to know the cause. Checking one of the logs I found this:

```
Quitting from lines 357-359 (06-raster-vector.Rmd) 
Error in FUN(X[[i]], ...) : 
  2 arguments passed to 'length' which requires 1
Calls: local ... aggregate -> aggregate.data.frame -> lapply -> FUN -> lapply
  |..............................                |  65% (06-raster-vector-26)  
                                                                                                                  
Execution halted
Error in Rscript_render(f, render_args, render_meta, add1, add2) : 
  Failed to compile 06-raster-vector.Rmd
Calls: <Anonymous> -> render_new_session -> Rscript_render
Execution halted
```

Source: https://github.com/geocompx/geocompr/actions/runs/4333585861/jobs/7566833108#step:4:2015

don't know for sure but seems like it could be something worth reporting?

**Comment by Robinlovelace** [comment] 2023-03-05 23:31
Or at least diagnosing with a reprex.

**Comment by Nowosad** [comment] 2023-03-06 10:54
I was wondering myself about it. I cannot reproduce it locally and (thus?) I think it is a temporary hiccup.

**Comment by Robinlovelace** [comment] 2023-03-06 16:01
Maybe Docker needs updating...

**Comment by Nowosad** [comment] 2023-03-08 09:05
https://github.com/rspatial/terra/issues/1054

**Comment by Robinlovelace** [comment] 2023-03-08 09:10
Good find! Worth keeping this issue open and we can fix as/when it's fixed upstream.

Alternative: pre-calculate the lengths and then use sum?

**Comment by Nowosad** [comment] 2023-03-08 09:12
No -- the length here is not a "geographic" length -- it is used to count the number of elements (points) in each raster cell. It should be fixed upstream.

**Comment by Robinlovelace** [comment] 2023-03-08 10:22
Ah yes of course.

**Comment by Nowosad** [comment] 2023-03-09 08:43
The issue was fixed upstream (https://github.com/rspatial/terra/issues/1054), but we will need to wait a month or two for the terra to be updated on CRAN.

**Closed by Nowosad** 2023-03-09 08:43 UTC
